### PR TITLE
Updates to cross program invocation

### PR DESCRIPTION
**Pull request by dadepo**
This PR adds the following:

- Updates the README to explain how the Cargo features is used to ensure there is only one `entrypoint!` when a Solana program depends on another Solana program
- Simplifies how the Cargo feature is used

### CODE REVIEW

**Comment by ngundotra** [comment]
Readme changes seem quite similar to #13, can you move your README changes to #13 only please?

Also, what do you mean by `lever` and `hand` crate? Otherwise, your additional docs look fine

**Comment by ngundotra** [comment]
Please add a comment to this PR explaining your changes

**Comment by dadepo** [comment]
> Readme changes seem quite similar to #13, can you move your README changes to #13 only please?

Done

> Also, what do you mean by `lever` and `hand` crate? Otherwise, your additional docs look fine

I was referring to [this](https://github.com/solana-developers/program-examples/tree/main/basics/cross-program-invocation/native/programs/lever)(lever) and [this](https://github.com/solana-developers/program-examples/tree/main/basics/cross-program-invocation/native/programs/hand)(hand). I referred to them by the rust convention of crates.

**Comment by realbuffalojoe** [comment]
If you moved this over from #10 can we close #10 and merge #13?

**Comment by dadepo** [comment]
> If you moved this over from #10 can we close #10 and merge #13?

sure!

Moved the changes here to #13. Closing as suggested

**Pull request closed without merging**
