### PR TITLE
Destroy Account Example

### PR DESCRIPTION
**Pull request by ohaddahan**
Adding an `Anchor` based example how to `create` and `close` (destroy) an `account` (specifically a `PDA`).

### CODE REVIEW

**Comment by ngundotra** [comment]
Looks great! Can you add:

* A short description of what `destroy-an-account` program does?
* The program's instruction interface
* Some of the relevant code snippets:


For example:
Closing an account
```rust
user.close(destination.to_account_info())?;
```

Fetching a possibly null account
```typescript
await program.accounts.user.fetchNullable(...);
```

cc @realbuffalojoe

**Comment by ohaddahan** [comment]
Added, `README.md` , thanks.

**Comment by ngundotra** [comment]
Looks much better thanks! Why are you using `processed` in your tests instead of `confirmed`?

**Comment by ngundotra** [comment]
Can you also update this PR with a description of your changes please?

**Comment by ohaddahan** [comment]
> Can you also update this PR with a description of your changes please?

Edited.

**Comment by ngundotra** [comment]
Can you call `close` on a non-PDA anchor account?

**Comment by ngundotra** [comment]
Looks good to me. cc Tagging @realbuffalojoe for final approval

**Comment by ngundotra** [comment]
Ofc! Great work @ohaddahan :) Thanks for your contribution

**Pull request merged**
