### PR TITLE
Add Counter Program example implementations

### PR DESCRIPTION
**Pull request by ngundotra**
Each of these examples also comes equipped with a framework TS SDK.

- anchor: uses anchor TS SDK
- seahorse: uses anchor TS SDK
- mpl-stack: uses metaplex-foundation's Solita to generate a TS SDK
- native: handwritten SDK that mimicks Solita structure.

It would be nice to also have a unified `package.json` script structure to setup testing & development for devs.
For `native` and `mpl-stack`, I have separated the testing & local-validator commands so debugging is easier

### CODE REVIEW

**Comment by ngundotra** [comment]
There's a little annoyance in the `mpl-stack` example, where we have to modify the generated typescript SDK after building it.

Waiting on https://github.com/metaplex-foundation/solita/issues/84 to fix

**Review by jpcaulfi — APPROVED** [review]
lgtm just had a few nit picks for ppl who will clone this down:
* Did you mean to include feature `init-if-needed` for anchor repo?
* What's `solana config set -ul`?

Love the native test layout, let's look into implementing for other examples :)

**Comment by ngundotra** [comment]
Removed `init-if-needed` feature flag, good catch! Initially I was trying to set the anchor example to match the native example exactly.

`solana config set -ul` sets the url to localhost

**Comment by jpcaulfi** [comment]
-ul shortcut blew my mind 🥇

**Pull request merged**
